### ISSUE TITLE
Wie im Filter html hinzufügen?

### ISSUE THREAD

**Issue by Olli** [heimrichhannot/contao-filter-bundle#10]
Ich möchte einen komfortablen JS Rangeslider nutzen. Dafür müsste ich zwischen den Filter aber HTML einfügen können. 
Ist das irgendwie zu realisieren (ähnlich einem html CE bei Contao)?

**Comment by Defcon0** [comment]
Du meinst sowas wie

https://refreshless.com/nouislider/

? Das haben wir bereits als Anbindung an den Filter umgesetzt als Choice und als Multi-Range-Filter :-)

https://github.com/heimrichhannot/contao-no-ui-slider-bundle

**Comment by Olli** [comment]
naja den NoUISlider habe ich auch eingebaut :) 
Ich werde das Modul dafür mal ausprobieren - danke für den Hinweis.
Was aber trotzdem noch bleibt ist das HTML ... manchmal möchte man z.B. noch Filteroptionen kommentieren.

**Comment by Olli** [comment]
Muss ich für das Teil noch irgendwas aktivieren? Ich habe das wie in der Anleitung gemacht ... 2 Textfelder und ne Multirange mit den 2 Textfeldern ausgewählt und noUiSlider Support angeschaltet . Auf der Webseite erscheinen die 2 Textfelder auch aber der Slider nicht. In der Anleitung steht noch, dass der Slider irgendwo angeschaltet werden muss. Ich weiß nur nicht wo. das JS davon wird zumindest nicht geladen.

**Comment by koertho** [comment]
@Olli Was das HTML anbelangt, hier werden Symfony Forms verwendet. Ich weiß nicht, wie man da Feld-Anmerkungen reinbekommt, aber geht sicher irgendwie. Events zum Anpassen sollte es genug geben.

Was den Slider-JS anbelangt, ich vermute, das hier ein Fehler in Verbindung mit Contao 4.9 vorliegt, der uns noch nihct aufgefallen ist, weil wir den Slider bisher nur in 4.4 eingesetzt haben

**Comment by Olli** [comment]
Ah ok. Also das betrifft dann zumindest auch eure JS für xhr Anfragen ... 
Ich hatte mal nach geschaut. Braucht man da encore? Wenn nicht brauche ich node auf dem Server? Da wird ja eine import Anweisung ausgeführt auf einen Ordner auf den der Webbrowser keinen zugriff hat - also muss es ggf vorher mit Webpack oder so gebaut werden (nehme ich an).

> @Olli Was das HTML anbelangt, hier werden Symfony Forms verwendet. Ich weiß nicht, wie man da Feld-Anmerkungen reinbekommt, aber geht sicher irgendwie. Events zum Anpassen sollte es genug geben.
Heißt das so viel "bau es dir selbst?" :-)

**Comment by koertho** [comment]
Mit Encore würdest du manche Probleme umschiffen, da unser Bundle da sehr breit von uns eingesetzt ist und wir die non-encore-versionen manchmal etwas vernachlässigen oder vergessen ;) Aber grundsätzlich bauen wir alles so, dass es nicht nötig ist. Es gab nur eine Änderung zwischen 4.4 und 4.9, dass Service in der condig.php nicht mehr richtig geladen werden. Und die haben wir teilweise genutzt, um zu prüfen, ob man im frontend oder backend ist. Sowas muss jetzt in hooks umgezogen werden (und das haben wir bei dem Slider noch nicht gemacht, die xhr geschichte haben wir eigentlich auch schon unter 4.9 im Einsatz).
Encore muss nicht auf dem Server laufen. Wir compilieren alle assets lokal und laden nur die kompilierten Assets hoch. Kannst dir gerne mal unser Encore-Bundle anschauen. Ich würde nicht mehr ohne arbeiten wollen ;)

> Heißt das so viel "bau es dir selbst?" :-)

Naja, es heißt, dass ich aktuell nicht wüsste, wie man da bei Symfony umsetzt und unser Bundle dafür aktuell keine Funktion hat, soweit ich weiß. Also im Prinzip: ja :P

**Comment by Olli** [comment]
Ich habe es mit Encore probiert ... das tut auch nicht. Ich habe aber gerade keinen Nerv zu testen warum das nicht tut. 
Ich habe mit dem Form-bundle und multi-range noch ein anderes Problem ... dazu mache ich aber einen weiteres Issue auf. 

Symfony-FormType: 
Schade sonst hätte ich mal eine Mail geschrieben ;-) 

Dann schließe ich das mal - optimal wäre wenn ich einfach das Template des Formulars anpassen könnte (https://github.com/heimrichhannot/contao-filter-bundle/issues/5) ... dann müsste ich nicht den Umweg gehen den Button einzubauen um den Slider zu starten.

**Comment by koertho** [comment]
@Olli Ich habe gerade mal das no-ui-slider-bundle angepasst (und dabei nen fiesen bug im encore bundle gefunden :sweat_smile: ), sollte jetzt auch unter 4.9 die Asset laden.

Encore ist am Anfang etwas heftig, aber der Lernaufwand lohnt sich meiner Meinung nach. Halte dich am besten an die Anleitung und Empfehlung in unserem Bundle, falls du es nutzen willst. Bei Frage, poste dort einfach ein Issue.

**Comment by Olli** [comment]
Ich bleibe bei meinem Code. 
Das bleibt übersichtlich und so mag ich es.
Trotzdem Danke.
