### ISSUE TITLE
DataContainer ... auch eigene möglich?

### ISSUE THREAD

**Issue by Olli** [heimrichhannot/contao-filter-bundle#29]
Hi,
ich habe Tabellen die nicht mit tl_ anfangen. Kann die aber bei der Auswahl Data-Container nicht finden (ich habe die in einem eigenen Modul angelegt und möchte lister, reader und filter für die bequeme Ausgabe nutzen).
Ist es möglich dass die Tabellen in der Data-Container Auswahl auftauchen?

**Comment by koertho** [comment]
Es können im aktuellen Stand nur DCA-basierte Tabellen ausgegeben werden. Und die müssen mit tl_ anfangen. Daher muss ich leider verneinen.

**Comment by Olli** [comment]
Hm das ist gerade extrem unschön. 
Kommt diese "Vorgabe" aus dem heimrichhannot/contao-utils-bundle oder ist das im Filter Bundle irgenwo hinterlegt? 
Ich glaube sollte nur etwas kleines sein, dass man überschreiben müsste.

**Comment by koertho** [comment]
Diese Vorgabe ist halt Contao-Standard. Ich bin mit nicht sicher, ob Contao mit DCA-Dateien umgeben kann, die nicht mit tl_ beginnen. Das Filter-Bundle nutzt DCA-Eigenschaften auch an anderer Stelle. Du kannst testweise den options-Callback von tl_filter_config.dataContainer überschreiben, aber das wird bestimmt andere Probleme nach sich ziehen.
Das einfachste wäre aber, sich einfach an den Standard zu halten ;)

**Comment by Olli** [comment]
Ja doch das kann es ... zumindest ist es überhaupt kein Problem DCAs zu definieren die sich nicht an tl_ halten (auch Relationen).
Auf den Callback bezog ich mich, beim contao Utils Bundle ['huh.utils.choice.data_container', 'getChoices']. Der scheint die Auswahl auf "tl_" zu filtern. 
Aber ok ... muss ich mal schauen, wie ich das jetzt löse ohne die Tabellen und Relationen umbenennen zu müssen. 
Thx for commenting :-)

**Comment by koertho** [comment]
Einfach das Callback überschreiben ;)

**Comment by Olli** [comment]
Das war ein sehr guter Hinweis durch den ich gemerkt habe, dass ich viel zu kompliziert gedacht habe.
Das hat tatsächlich funktioniert. 
Man muss dann in der Config noch die Modelfiles mit require_cone laden weil Contao die Filenamen anhand des Tabellennamen ableitet. 
Thx.
