### ISSUE TITLE
Umstellung auf POST → Fehler → fehlendes Token

### ISSUE THREAD

**Issue by Olli** [heimrichhannot/contao-filter-bundle#3]
Contao 4.9.8, 1.5.4 contao-filter-bundle

Wenn ich den Filter auf POST umstelle, gibt es wegen eines fehlenden Tokens einen Fehler " Ungültiges Anfrage-Token ".

**Comment by Defcon0** [comment]
Bitte betreibe den Filter nur im GET-Modus. Das ist noch vom Start, wird nicht mehr supportet und kommt bald raus.
