### ISSUE TITLE
Resetbutton wird nicht angezeigt 

### ISSUE THREAD

**Issue by Olli** [heimrichhannot/contao-filter-bundle#7]
Contao 4.9.9
Filter Bundle Version 1.5.4

Ich habe in den Filter einen Reset Button eingebaut. Der wird nicht angezeigt. Die Config des Buttons siehe Anhang:
![Screenshot_2020-10-29 Filter- Sortierkonfigurationen](https://user-images.githubusercontent.com/1754/97566138-44a48980-19de-11eb-859b-7aafd06da740.png)

**Comment by koertho** [comment]
Rein theoretisch sollte es den anzeigen. Lass sich schwierig sagen. Hast du ein custom form theme?

**Comment by Olli** [comment]
Was ist ein Custom Form Theme? Meinst du ob ich das HTML angepasst habe was das Formular generiert?

**Comment by koertho** [comment]
Wir arbeiten hier mit Symfony forms. Da kann man die Form Themes anpassen, also die Darstellung/Ausgabe.
